name: "CI"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v27
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: nix-build
    - uses: actions/upload-artifact@v4
      with:
        name: mt.olympOS.img
        path: result/bin/mt.olympOS.img
    - uses: actions/checkout@v3
    - uses: GirishCodeAlchemy/githubaction-workflow-status-capture@v2.0
