name: "CI"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v27
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: nix-build && chmod +x tests/check-boot.sh && bash tests/check-boot.sh
    - uses: actions/upload-artifact@v4
      with:
        name: btl1.asm
        path: mt.olympOS.img
